import numpy as np

BASESTATION_WEBSOCKET_URL = 'ws://localhost:3000'
CAMERA_MODELS_FILE_PATH = '../data/camera_models/camera_models.json'
TEST_IMAGE_DIRECTORY_PATH = '../data/images/full_scene/*.jpg'
TABLE_CAMERA_MODEL_ID = 0
CAMERA_ID = 1
CAP_WIDTH = 1280
CAP_HEIGHT = 800

# HSV COLOR
LOWER_GREEN_HSV = np.array([45, 50, 40])
UPPER_GREEN_HSV = np.array([80, 255, 255])

LOWER_FUCHSIA_HSV = np.array([120, 100, 100])
HIGHER_FUCHSIA_HSV = np.array([180, 255, 255])

# ROBOT MARKERS SPECIFICATIONS
NUMBER_OF_MARKERS = 3
TARGET_MIN_DISTANCE = 12
TARGET_MIN_RADIUS = 5
TARGET_MAX_RADIUS = 30

# TABLE SPECIFICATIONS
MIN_TABLE_AREA = 70000

